[project]
name = "daily-wallpaper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coloraide>=5.1",
    "numpy>=2.3.4",
    "pillow>=12.0.0",
    "requests>=2.32.5",
]
